# Generated by Django 4.0 on 2022-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(max_length=12)),
                ('nome', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('armario', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
